### ISSUE TITLE
LSTM Generator- implementation

### ISSUE THREAD

**Issue by Adrianc1234** [Adrianc1234/Final_Integrate_Project#2]
Implement the Chart_lstm mario notebook

**Comment by GabrielISB** [comment]
Implementation done

**Comment by GabrielISB** [comment]
LSTM Overfitted we must try again

**Comment by Adrianc1234** [comment]
It looks so bad, so we need to look for other implementation

**Comment by GabrielISB** [comment]
Hmmm we might just get a better design of the model
