### ISSUE TITLE
Researching

### ISSUE THREAD

**Issue by Adrianc1234** [Adrianc1234/Final_Integrate_Project#3]
Investigation about new Neural Networks for classification
Investigation about new Neural Networks for text generator

**Comment by mejarcito** [comment]
Found a better model for the classification: BERT classification.

**Comment by Adrianc1234** [comment]
I found a better model for generator called RNN, it looks better than the first one

**Comment by Adrianc1234** [comment]
I will implement that one

**Comment by Adrianc1234** [comment]
So we have both algorithms to implements, lets do it.
