### ISSUE TITLE
BERT implementation

### ISSUE THREAD

**Issue by Adrianc1234** [Adrianc1234/Final_Integrate_Project#9]

**Comment by AlexHurtado23** [comment]
I just gonna implement the BERT network with @GabrielISB

**Comment by GabrielISB** [comment]
BERT network implemented and training

**Comment by GabrielISB** [comment]
![image](https://user-images.githubusercontent.com/61764384/205352666-1a8f413a-a261-4f23-91f4-420a3f1d3b12.png)
Looks good

**Comment by Adrianc1234** [comment]
It looks better that the first one, so let stay with it. I will close this issue.
